//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDS.Infraestructure.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoProducto
    {
        public int CodPedidoProducto { get; set; }
        public int CodPtoPreparacion { get; set; }
        public Nullable<int> CodEstadoPedidoProd { get; set; }
        public string CodPedido { get; set; }
        public string CodProducto { get; set; }
        public string CodOperador { get; set; }
        public string CodPropiedad { get; set; }
        public System.DateTime HoraSalida { get; set; }
        public string Observaciones { get; set; }
        public bool EstadoRegistro { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Parametrica Parametrica { get; set; }
        public virtual PtoPreparacion PtoPreparacion { get; set; }
    }
}
