//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDS.Infraestructure.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProductoPedido
    {
        public string lCombo { get; set; }
        public string tCodigoPedido { get; set; }
        public string tItem { get; set; }
        public string tItemCombo { get; set; }
        public Nullable<int> nOrden { get; set; }
        public Nullable<double> nCantidad { get; set; }
        public string tCodigoGrupo { get; set; }
        public string tDescGrupo { get; set; }
        public string tCodigoSubGrupo { get; set; }
        public string tDescSubGrupo { get; set; }
        public string tCodigoProducto { get; set; }
        public string tDetallado { get; set; }
        public string tCodigoPropiedad { get; set; }
        public string tDescPropiedad { get; set; }
        public string tTipoPedido { get; set; }
        public string tDescTipoPedido { get; set; }
        public string tArea { get; set; }
        public string tDescArea { get; set; }
        public string tUnidadNegocio { get; set; }
        public string tDescUnidadNegocio { get; set; }
        public string tEstadoItem { get; set; }
    }
}
