//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDS.Infraestructure.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Producto
    {
        public string CodProducto { get; set; }
        public string DescProducto { get; set; }
        public string CodGrupo { get; set; }
        public string DescGrupo { get; set; }
        public string CodSubGrupo { get; set; }
        public string DescSubGrupo { get; set; }
        public string CodTipoProducto { get; set; }
        public string DescTipoProducto { get; set; }
        public string CodArea { get; set; }
        public string DescArea { get; set; }
        public string CodUnidadNegocio { get; set; }
        public string DescUnidadNegocio { get; set; }
        public Nullable<bool> Combo { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
