//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDS.Infraestructure.Data.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    
    public partial class MainModelContext : DbContext
    {
        public MainModelContext()
            : base("name=MainModelContext")
        {
    }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Iconografia> Iconografia { get; set; }
        public DbSet<OperadorPropiedad> OperadorPropiedad { get; set; }
        public DbSet<Parametrica> Parametrica { get; set; }
        public DbSet<PedidoProducto> PedidoProducto { get; set; }
        public DbSet<PtoPreparacion> PtoPreparacion { get; set; }
        public DbSet<TipoParametrica> TipoParametrica { get; set; }
        public DbSet<vw_Grupo> vw_Grupo { get; set; }
        public DbSet<vw_Producto> vw_Producto { get; set; }
        public DbSet<vw_ProductoPedido> vw_ProductoPedido { get; set; }
        public DbSet<vw_SubGrupo> vw_SubGrupo { get; set; }
        public DbSet<vw_UnidadNegocio> vw_UnidadNegocio { get; set; }
        public DbSet<ProductoPtoPrep> ProductoPtoPrep { get; set; }
        public DbSet<TiempoConsumo> TiempoConsumo { get; set; }
    
        public virtual int sp_add_ptopreparacion(string p_CodUnidadNegocio, string p_Nombre, string p_Descripcion, string p_UsuarioCreacion)
        {
            var p_CodUnidadNegocioParameter = p_CodUnidadNegocio != null ?
                new ObjectParameter("p_CodUnidadNegocio", p_CodUnidadNegocio) :
                new ObjectParameter("p_CodUnidadNegocio", typeof(string));
    
            var p_NombreParameter = p_Nombre != null ?
                new ObjectParameter("p_Nombre", p_Nombre) :
                new ObjectParameter("p_Nombre", typeof(string));
    
            var p_DescripcionParameter = p_Descripcion != null ?
                new ObjectParameter("p_Descripcion", p_Descripcion) :
                new ObjectParameter("p_Descripcion", typeof(string));
    
            var p_UsuarioCreacionParameter = p_UsuarioCreacion != null ?
                new ObjectParameter("p_UsuarioCreacion", p_UsuarioCreacion) :
                new ObjectParameter("p_UsuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_add_ptopreparacion", p_CodUnidadNegocioParameter, p_NombreParameter, p_DescripcionParameter, p_UsuarioCreacionParameter);
        }
    
        public virtual int sp_add_productoptoprep(Nullable<int> p_CodPtoPreparacion, string p_CodProducto, Nullable<int> p_IndEnsamblado, Nullable<int> p_TiempoPrepDirecto, Nullable<int> p_TiempoPrepSegundo, Nullable<int> p_MinCantidad, Nullable<int> p_MaxCantidad, string p_UsuarioCreacion)
        {
            var p_CodPtoPreparacionParameter = p_CodPtoPreparacion.HasValue ?
                new ObjectParameter("p_CodPtoPreparacion", p_CodPtoPreparacion) :
                new ObjectParameter("p_CodPtoPreparacion", typeof(int));
    
            var p_CodProductoParameter = p_CodProducto != null ?
                new ObjectParameter("p_CodProducto", p_CodProducto) :
                new ObjectParameter("p_CodProducto", typeof(string));
    
            var p_IndEnsambladoParameter = p_IndEnsamblado.HasValue ?
                new ObjectParameter("p_IndEnsamblado", p_IndEnsamblado) :
                new ObjectParameter("p_IndEnsamblado", typeof(int));
    
            var p_TiempoPrepDirectoParameter = p_TiempoPrepDirecto.HasValue ?
                new ObjectParameter("p_TiempoPrepDirecto", p_TiempoPrepDirecto) :
                new ObjectParameter("p_TiempoPrepDirecto", typeof(int));
    
            var p_TiempoPrepSegundoParameter = p_TiempoPrepSegundo.HasValue ?
                new ObjectParameter("p_TiempoPrepSegundo", p_TiempoPrepSegundo) :
                new ObjectParameter("p_TiempoPrepSegundo", typeof(int));
    
            var p_MinCantidadParameter = p_MinCantidad.HasValue ?
                new ObjectParameter("p_MinCantidad", p_MinCantidad) :
                new ObjectParameter("p_MinCantidad", typeof(int));
    
            var p_MaxCantidadParameter = p_MaxCantidad.HasValue ?
                new ObjectParameter("p_MaxCantidad", p_MaxCantidad) :
                new ObjectParameter("p_MaxCantidad", typeof(int));
    
            var p_UsuarioCreacionParameter = p_UsuarioCreacion != null ?
                new ObjectParameter("p_UsuarioCreacion", p_UsuarioCreacion) :
                new ObjectParameter("p_UsuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_add_productoptoprep", p_CodPtoPreparacionParameter, p_CodProductoParameter, p_IndEnsambladoParameter, p_TiempoPrepDirectoParameter, p_TiempoPrepSegundoParameter, p_MinCantidadParameter, p_MaxCantidadParameter, p_UsuarioCreacionParameter);
        }
    
        public virtual ObjectResult<sp_get_aut_producto_Result> sp_get_aut_producto(string p_CodUnidadNegocio, string p_DescProducto, Nullable<short> p_EndIndex)
        {
            var p_CodUnidadNegocioParameter = p_CodUnidadNegocio != null ?
                new ObjectParameter("p_CodUnidadNegocio", p_CodUnidadNegocio) :
                new ObjectParameter("p_CodUnidadNegocio", typeof(string));
    
            var p_DescProductoParameter = p_DescProducto != null ?
                new ObjectParameter("p_DescProducto", p_DescProducto) :
                new ObjectParameter("p_DescProducto", typeof(string));
    
            var p_EndIndexParameter = p_EndIndex.HasValue ?
                new ObjectParameter("p_EndIndex", p_EndIndex) :
                new ObjectParameter("p_EndIndex", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_aut_producto_Result>("sp_get_aut_producto", p_CodUnidadNegocioParameter, p_DescProductoParameter, p_EndIndexParameter);
        }
    
        public virtual ObjectResult<sp_get_pag_ptopreparacion_Result> sp_get_pag_ptopreparacion(string p_CodUnidadNegocio, Nullable<short> p_StartIndex, Nullable<short> p_EndIndex, string p_SortCol, string p_SortOrder, ObjectParameter p_TotalDisplayRecords, ObjectParameter p_TotalRecords)
        {
            var p_CodUnidadNegocioParameter = p_CodUnidadNegocio != null ?
                new ObjectParameter("p_CodUnidadNegocio", p_CodUnidadNegocio) :
                new ObjectParameter("p_CodUnidadNegocio", typeof(string));
    
            var p_StartIndexParameter = p_StartIndex.HasValue ?
                new ObjectParameter("p_StartIndex", p_StartIndex) :
                new ObjectParameter("p_StartIndex", typeof(short));
    
            var p_EndIndexParameter = p_EndIndex.HasValue ?
                new ObjectParameter("p_EndIndex", p_EndIndex) :
                new ObjectParameter("p_EndIndex", typeof(short));
    
            var p_SortColParameter = p_SortCol != null ?
                new ObjectParameter("p_SortCol", p_SortCol) :
                new ObjectParameter("p_SortCol", typeof(string));
    
            var p_SortOrderParameter = p_SortOrder != null ?
                new ObjectParameter("p_SortOrder", p_SortOrder) :
                new ObjectParameter("p_SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_pag_ptopreparacion_Result>("sp_get_pag_ptopreparacion", p_CodUnidadNegocioParameter, p_StartIndexParameter, p_EndIndexParameter, p_SortColParameter, p_SortOrderParameter, p_TotalDisplayRecords, p_TotalRecords);
        }
    
        public virtual ObjectResult<sp_get_productoptoprep_Result> sp_get_productoptoprep(Nullable<int> p_CodProductoPtoPrep)
        {
            var p_CodProductoPtoPrepParameter = p_CodProductoPtoPrep.HasValue ?
                new ObjectParameter("p_CodProductoPtoPrep", p_CodProductoPtoPrep) :
                new ObjectParameter("p_CodProductoPtoPrep", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_productoptoprep_Result>("sp_get_productoptoprep", p_CodProductoPtoPrepParameter);
        }
    
        public virtual ObjectResult<sp_get_pag_productoptoprep_Result> sp_get_pag_productoptoprep(string p_CodUnidadNegocio, Nullable<int> p_CodPtoPreparacion, Nullable<short> p_StartIndex, Nullable<short> p_EndIndex, string p_SortCol, string p_SortOrder, ObjectParameter p_TotalDisplayRecords, ObjectParameter p_TotalRecords)
        {
            var p_CodUnidadNegocioParameter = p_CodUnidadNegocio != null ?
                new ObjectParameter("p_CodUnidadNegocio", p_CodUnidadNegocio) :
                new ObjectParameter("p_CodUnidadNegocio", typeof(string));
    
            var p_CodPtoPreparacionParameter = p_CodPtoPreparacion.HasValue ?
                new ObjectParameter("p_CodPtoPreparacion", p_CodPtoPreparacion) :
                new ObjectParameter("p_CodPtoPreparacion", typeof(int));
    
            var p_StartIndexParameter = p_StartIndex.HasValue ?
                new ObjectParameter("p_StartIndex", p_StartIndex) :
                new ObjectParameter("p_StartIndex", typeof(short));
    
            var p_EndIndexParameter = p_EndIndex.HasValue ?
                new ObjectParameter("p_EndIndex", p_EndIndex) :
                new ObjectParameter("p_EndIndex", typeof(short));
    
            var p_SortColParameter = p_SortCol != null ?
                new ObjectParameter("p_SortCol", p_SortCol) :
                new ObjectParameter("p_SortCol", typeof(string));
    
            var p_SortOrderParameter = p_SortOrder != null ?
                new ObjectParameter("p_SortOrder", p_SortOrder) :
                new ObjectParameter("p_SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_pag_productoptoprep_Result>("sp_get_pag_productoptoprep", p_CodUnidadNegocioParameter, p_CodPtoPreparacionParameter, p_StartIndexParameter, p_EndIndexParameter, p_SortColParameter, p_SortOrderParameter, p_TotalDisplayRecords, p_TotalRecords);
        }
    
        public virtual ObjectResult<sp_get_pag_pedidoproducto_Result> sp_get_pag_pedidoproducto(Nullable<int> p_CodPtoPreparacion, Nullable<short> p_StartIndex, Nullable<short> p_EndIndex, string p_SortCol, string p_SortOrder, ObjectParameter p_TotalDisplayRecords, ObjectParameter p_TotalRecords)
        {
            var p_CodPtoPreparacionParameter = p_CodPtoPreparacion.HasValue ?
                new ObjectParameter("p_CodPtoPreparacion", p_CodPtoPreparacion) :
                new ObjectParameter("p_CodPtoPreparacion", typeof(int));
    
            var p_StartIndexParameter = p_StartIndex.HasValue ?
                new ObjectParameter("p_StartIndex", p_StartIndex) :
                new ObjectParameter("p_StartIndex", typeof(short));
    
            var p_EndIndexParameter = p_EndIndex.HasValue ?
                new ObjectParameter("p_EndIndex", p_EndIndex) :
                new ObjectParameter("p_EndIndex", typeof(short));
    
            var p_SortColParameter = p_SortCol != null ?
                new ObjectParameter("p_SortCol", p_SortCol) :
                new ObjectParameter("p_SortCol", typeof(string));
    
            var p_SortOrderParameter = p_SortOrder != null ?
                new ObjectParameter("p_SortOrder", p_SortOrder) :
                new ObjectParameter("p_SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_pag_pedidoproducto_Result>("sp_get_pag_pedidoproducto", p_CodPtoPreparacionParameter, p_StartIndexParameter, p_EndIndexParameter, p_SortColParameter, p_SortOrderParameter, p_TotalDisplayRecords, p_TotalRecords);
        }
    
        public virtual ObjectResult<sp_get_grupo_maestro_Result> sp_get_grupo_maestro(string p_CodGrupo, Nullable<short> p_StartIndex, Nullable<short> p_EndIndex, string p_SortCol, string p_SortOrder, ObjectParameter p_TotalDisplayRecords, ObjectParameter p_TotalRecords)
        {
            var p_CodGrupoParameter = p_CodGrupo != null ?
                new ObjectParameter("p_CodGrupo", p_CodGrupo) :
                new ObjectParameter("p_CodGrupo", typeof(string));
    
            var p_StartIndexParameter = p_StartIndex.HasValue ?
                new ObjectParameter("p_StartIndex", p_StartIndex) :
                new ObjectParameter("p_StartIndex", typeof(short));
    
            var p_EndIndexParameter = p_EndIndex.HasValue ?
                new ObjectParameter("p_EndIndex", p_EndIndex) :
                new ObjectParameter("p_EndIndex", typeof(short));
    
            var p_SortColParameter = p_SortCol != null ?
                new ObjectParameter("p_SortCol", p_SortCol) :
                new ObjectParameter("p_SortCol", typeof(string));
    
            var p_SortOrderParameter = p_SortOrder != null ?
                new ObjectParameter("p_SortOrder", p_SortOrder) :
                new ObjectParameter("p_SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_grupo_maestro_Result>("sp_get_grupo_maestro", p_CodGrupoParameter, p_StartIndexParameter, p_EndIndexParameter, p_SortColParameter, p_SortOrderParameter, p_TotalDisplayRecords, p_TotalRecords);
        }
    
        public virtual ObjectResult<sp_get_producto_maestro_Result> sp_get_producto_maestro(string p_CodGrupo, string p_CodSubGrupo, string p_CodProducto, string p_DescProducto, Nullable<short> p_StartIndex, Nullable<short> p_EndIndex, string p_SortCol, string p_SortOrder, ObjectParameter p_TotalDisplayRecords, ObjectParameter p_TotalRecords)
        {
            var p_CodGrupoParameter = p_CodGrupo != null ?
                new ObjectParameter("p_CodGrupo", p_CodGrupo) :
                new ObjectParameter("p_CodGrupo", typeof(string));
    
            var p_CodSubGrupoParameter = p_CodSubGrupo != null ?
                new ObjectParameter("p_CodSubGrupo", p_CodSubGrupo) :
                new ObjectParameter("p_CodSubGrupo", typeof(string));
    
            var p_CodProductoParameter = p_CodProducto != null ?
                new ObjectParameter("p_CodProducto", p_CodProducto) :
                new ObjectParameter("p_CodProducto", typeof(string));
    
            var p_DescProductoParameter = p_DescProducto != null ?
                new ObjectParameter("p_DescProducto", p_DescProducto) :
                new ObjectParameter("p_DescProducto", typeof(string));
    
            var p_StartIndexParameter = p_StartIndex.HasValue ?
                new ObjectParameter("p_StartIndex", p_StartIndex) :
                new ObjectParameter("p_StartIndex", typeof(short));
    
            var p_EndIndexParameter = p_EndIndex.HasValue ?
                new ObjectParameter("p_EndIndex", p_EndIndex) :
                new ObjectParameter("p_EndIndex", typeof(short));
    
            var p_SortColParameter = p_SortCol != null ?
                new ObjectParameter("p_SortCol", p_SortCol) :
                new ObjectParameter("p_SortCol", typeof(string));
    
            var p_SortOrderParameter = p_SortOrder != null ?
                new ObjectParameter("p_SortOrder", p_SortOrder) :
                new ObjectParameter("p_SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_producto_maestro_Result>("sp_get_producto_maestro", p_CodGrupoParameter, p_CodSubGrupoParameter, p_CodProductoParameter, p_DescProductoParameter, p_StartIndexParameter, p_EndIndexParameter, p_SortColParameter, p_SortOrderParameter, p_TotalDisplayRecords, p_TotalRecords);
        }
    
        public virtual ObjectResult<sp_get_subgrupo_maestro_Result> sp_get_subgrupo_maestro(string p_CodGrupo, string p_CodSubGrupo, Nullable<short> p_StartIndex, Nullable<short> p_EndIndex, string p_SortCol, string p_SortOrder, ObjectParameter p_TotalDisplayRecords, ObjectParameter p_TotalRecords)
        {
            var p_CodGrupoParameter = p_CodGrupo != null ?
                new ObjectParameter("p_CodGrupo", p_CodGrupo) :
                new ObjectParameter("p_CodGrupo", typeof(string));
    
            var p_CodSubGrupoParameter = p_CodSubGrupo != null ?
                new ObjectParameter("p_CodSubGrupo", p_CodSubGrupo) :
                new ObjectParameter("p_CodSubGrupo", typeof(string));
    
            var p_StartIndexParameter = p_StartIndex.HasValue ?
                new ObjectParameter("p_StartIndex", p_StartIndex) :
                new ObjectParameter("p_StartIndex", typeof(short));
    
            var p_EndIndexParameter = p_EndIndex.HasValue ?
                new ObjectParameter("p_EndIndex", p_EndIndex) :
                new ObjectParameter("p_EndIndex", typeof(short));
    
            var p_SortColParameter = p_SortCol != null ?
                new ObjectParameter("p_SortCol", p_SortCol) :
                new ObjectParameter("p_SortCol", typeof(string));
    
            var p_SortOrderParameter = p_SortOrder != null ?
                new ObjectParameter("p_SortOrder", p_SortOrder) :
                new ObjectParameter("p_SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_subgrupo_maestro_Result>("sp_get_subgrupo_maestro", p_CodGrupoParameter, p_CodSubGrupoParameter, p_StartIndexParameter, p_EndIndexParameter, p_SortColParameter, p_SortOrderParameter, p_TotalDisplayRecords, p_TotalRecords);
        }
    
        public virtual ObjectResult<sp_get_tiempoconsumo_grupo_Result> sp_get_tiempoconsumo_grupo(string p_CodGrupo, string p_CodPropiedad, Nullable<int> p_CantPlatos, Nullable<short> p_StartIndex, Nullable<short> p_EndIndex, string p_SortCol, string p_SortOrder, ObjectParameter p_TotalDisplayRecords, ObjectParameter p_TotalRecords)
        {
            var p_CodGrupoParameter = p_CodGrupo != null ?
                new ObjectParameter("p_CodGrupo", p_CodGrupo) :
                new ObjectParameter("p_CodGrupo", typeof(string));
    
            var p_CodPropiedadParameter = p_CodPropiedad != null ?
                new ObjectParameter("p_CodPropiedad", p_CodPropiedad) :
                new ObjectParameter("p_CodPropiedad", typeof(string));
    
            var p_CantPlatosParameter = p_CantPlatos.HasValue ?
                new ObjectParameter("p_CantPlatos", p_CantPlatos) :
                new ObjectParameter("p_CantPlatos", typeof(int));
    
            var p_StartIndexParameter = p_StartIndex.HasValue ?
                new ObjectParameter("p_StartIndex", p_StartIndex) :
                new ObjectParameter("p_StartIndex", typeof(short));
    
            var p_EndIndexParameter = p_EndIndex.HasValue ?
                new ObjectParameter("p_EndIndex", p_EndIndex) :
                new ObjectParameter("p_EndIndex", typeof(short));
    
            var p_SortColParameter = p_SortCol != null ?
                new ObjectParameter("p_SortCol", p_SortCol) :
                new ObjectParameter("p_SortCol", typeof(string));
    
            var p_SortOrderParameter = p_SortOrder != null ?
                new ObjectParameter("p_SortOrder", p_SortOrder) :
                new ObjectParameter("p_SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_tiempoconsumo_grupo_Result>("sp_get_tiempoconsumo_grupo", p_CodGrupoParameter, p_CodPropiedadParameter, p_CantPlatosParameter, p_StartIndexParameter, p_EndIndexParameter, p_SortColParameter, p_SortOrderParameter, p_TotalDisplayRecords, p_TotalRecords);
        }
    
        public virtual ObjectResult<sp_get_tiempoconsumo_producto_Result> sp_get_tiempoconsumo_producto(string p_CodGrupo, string p_CodSubGrupo, string p_CodPropiedad, string p_CodProducto, string p_DescProducto, Nullable<int> p_CantPlatos, Nullable<short> p_StartIndex, Nullable<short> p_EndIndex, string p_SortCol, string p_SortOrder, ObjectParameter p_TotalDisplayRecords, ObjectParameter p_TotalRecords)
        {
            var p_CodGrupoParameter = p_CodGrupo != null ?
                new ObjectParameter("p_CodGrupo", p_CodGrupo) :
                new ObjectParameter("p_CodGrupo", typeof(string));
    
            var p_CodSubGrupoParameter = p_CodSubGrupo != null ?
                new ObjectParameter("p_CodSubGrupo", p_CodSubGrupo) :
                new ObjectParameter("p_CodSubGrupo", typeof(string));
    
            var p_CodPropiedadParameter = p_CodPropiedad != null ?
                new ObjectParameter("p_CodPropiedad", p_CodPropiedad) :
                new ObjectParameter("p_CodPropiedad", typeof(string));
    
            var p_CodProductoParameter = p_CodProducto != null ?
                new ObjectParameter("p_CodProducto", p_CodProducto) :
                new ObjectParameter("p_CodProducto", typeof(string));
    
            var p_DescProductoParameter = p_DescProducto != null ?
                new ObjectParameter("p_DescProducto", p_DescProducto) :
                new ObjectParameter("p_DescProducto", typeof(string));
    
            var p_CantPlatosParameter = p_CantPlatos.HasValue ?
                new ObjectParameter("p_CantPlatos", p_CantPlatos) :
                new ObjectParameter("p_CantPlatos", typeof(int));
    
            var p_StartIndexParameter = p_StartIndex.HasValue ?
                new ObjectParameter("p_StartIndex", p_StartIndex) :
                new ObjectParameter("p_StartIndex", typeof(short));
    
            var p_EndIndexParameter = p_EndIndex.HasValue ?
                new ObjectParameter("p_EndIndex", p_EndIndex) :
                new ObjectParameter("p_EndIndex", typeof(short));
    
            var p_SortColParameter = p_SortCol != null ?
                new ObjectParameter("p_SortCol", p_SortCol) :
                new ObjectParameter("p_SortCol", typeof(string));
    
            var p_SortOrderParameter = p_SortOrder != null ?
                new ObjectParameter("p_SortOrder", p_SortOrder) :
                new ObjectParameter("p_SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_tiempoconsumo_producto_Result>("sp_get_tiempoconsumo_producto", p_CodGrupoParameter, p_CodSubGrupoParameter, p_CodPropiedadParameter, p_CodProductoParameter, p_DescProductoParameter, p_CantPlatosParameter, p_StartIndexParameter, p_EndIndexParameter, p_SortColParameter, p_SortOrderParameter, p_TotalDisplayRecords, p_TotalRecords);
        }
    
        public virtual ObjectResult<sp_get_tiempoconsumo_subgrupo_Result> sp_get_tiempoconsumo_subgrupo(string p_CodSubGrupo, string p_CodGrupo, string p_CodPropiedad, Nullable<int> p_CantPlatos, Nullable<short> p_StartIndex, Nullable<short> p_EndIndex, string p_SortCol, string p_SortOrder, ObjectParameter p_TotalDisplayRecords, ObjectParameter p_TotalRecords)
        {
            var p_CodSubGrupoParameter = p_CodSubGrupo != null ?
                new ObjectParameter("p_CodSubGrupo", p_CodSubGrupo) :
                new ObjectParameter("p_CodSubGrupo", typeof(string));
    
            var p_CodGrupoParameter = p_CodGrupo != null ?
                new ObjectParameter("p_CodGrupo", p_CodGrupo) :
                new ObjectParameter("p_CodGrupo", typeof(string));
    
            var p_CodPropiedadParameter = p_CodPropiedad != null ?
                new ObjectParameter("p_CodPropiedad", p_CodPropiedad) :
                new ObjectParameter("p_CodPropiedad", typeof(string));
    
            var p_CantPlatosParameter = p_CantPlatos.HasValue ?
                new ObjectParameter("p_CantPlatos", p_CantPlatos) :
                new ObjectParameter("p_CantPlatos", typeof(int));
    
            var p_StartIndexParameter = p_StartIndex.HasValue ?
                new ObjectParameter("p_StartIndex", p_StartIndex) :
                new ObjectParameter("p_StartIndex", typeof(short));
    
            var p_EndIndexParameter = p_EndIndex.HasValue ?
                new ObjectParameter("p_EndIndex", p_EndIndex) :
                new ObjectParameter("p_EndIndex", typeof(short));
    
            var p_SortColParameter = p_SortCol != null ?
                new ObjectParameter("p_SortCol", p_SortCol) :
                new ObjectParameter("p_SortCol", typeof(string));
    
            var p_SortOrderParameter = p_SortOrder != null ?
                new ObjectParameter("p_SortOrder", p_SortOrder) :
                new ObjectParameter("p_SortOrder", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_tiempoconsumo_subgrupo_Result>("sp_get_tiempoconsumo_subgrupo", p_CodSubGrupoParameter, p_CodGrupoParameter, p_CodPropiedadParameter, p_CantPlatosParameter, p_StartIndexParameter, p_EndIndexParameter, p_SortColParameter, p_SortOrderParameter, p_TotalDisplayRecords, p_TotalRecords);
        }
    
        public virtual int sp_add_tiempoconsumo(Nullable<int> p_CodTiempoConsumo, string p_CodGrupo, string p_CodSubGrupo, string p_CodProducto, string p_CodPropiedad, Nullable<int> p_CantPlatos, Nullable<int> p_MinComensales, Nullable<int> p_MaxComensales, Nullable<int> p_Tiempo, string p_UsuarioCreacion)
        {
            var p_CodTiempoConsumoParameter = p_CodTiempoConsumo.HasValue ?
                new ObjectParameter("p_CodTiempoConsumo", p_CodTiempoConsumo) :
                new ObjectParameter("p_CodTiempoConsumo", typeof(int));
    
            var p_CodGrupoParameter = p_CodGrupo != null ?
                new ObjectParameter("p_CodGrupo", p_CodGrupo) :
                new ObjectParameter("p_CodGrupo", typeof(string));
    
            var p_CodSubGrupoParameter = p_CodSubGrupo != null ?
                new ObjectParameter("p_CodSubGrupo", p_CodSubGrupo) :
                new ObjectParameter("p_CodSubGrupo", typeof(string));
    
            var p_CodProductoParameter = p_CodProducto != null ?
                new ObjectParameter("p_CodProducto", p_CodProducto) :
                new ObjectParameter("p_CodProducto", typeof(string));
    
            var p_CodPropiedadParameter = p_CodPropiedad != null ?
                new ObjectParameter("p_CodPropiedad", p_CodPropiedad) :
                new ObjectParameter("p_CodPropiedad", typeof(string));
    
            var p_CantPlatosParameter = p_CantPlatos.HasValue ?
                new ObjectParameter("p_CantPlatos", p_CantPlatos) :
                new ObjectParameter("p_CantPlatos", typeof(int));
    
            var p_MinComensalesParameter = p_MinComensales.HasValue ?
                new ObjectParameter("p_MinComensales", p_MinComensales) :
                new ObjectParameter("p_MinComensales", typeof(int));
    
            var p_MaxComensalesParameter = p_MaxComensales.HasValue ?
                new ObjectParameter("p_MaxComensales", p_MaxComensales) :
                new ObjectParameter("p_MaxComensales", typeof(int));
    
            var p_TiempoParameter = p_Tiempo.HasValue ?
                new ObjectParameter("p_Tiempo", p_Tiempo) :
                new ObjectParameter("p_Tiempo", typeof(int));
    
            var p_UsuarioCreacionParameter = p_UsuarioCreacion != null ?
                new ObjectParameter("p_UsuarioCreacion", p_UsuarioCreacion) :
                new ObjectParameter("p_UsuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_add_tiempoconsumo", p_CodTiempoConsumoParameter, p_CodGrupoParameter, p_CodSubGrupoParameter, p_CodProductoParameter, p_CodPropiedadParameter, p_CantPlatosParameter, p_MinComensalesParameter, p_MaxComensalesParameter, p_TiempoParameter, p_UsuarioCreacionParameter);
        }
    }
}
